(load "~/.emacs.d/elpa/sr-speedbar-0.1.8/sr-speedbar.el")
(require 'sr-speedbar)
(setq speedbar-show-unknown-files t)
(setq speedbar-use-images nil)
(setq sr-speedbar-right-side nil)
(setq sr-speedbar-max-width 60)
(setq sr-speedbar-default-width 40)
(global-set-key (kbd "C-x O") 'sr-speedbar-open) 
(global-set-key (kbd "C-x C") 'sr-speedbar-close) 
;;(sr-speedbar-open)
